### ISSUE TITLE
Advanced TIMIT handling 

### ISSUE THREAD

**Issue by cyrusae** [cyrusae/helpAR#5]
Statement of intent per current notes to self:
```
# TODO: add rest of TIMIT: 
### PAU, EPI, H# lack relevant IPA equivalents
### AX-H, BCL, DCL, GCL, HV, KCL, PCL, TCL are not present here and do, strictly speaking, have IPA equivalents that could be included 
### In practice I'm not sure the additional symbols would parse correctly for R's sake from a Unicode perspective but they *could* be added as options to have simplified to the vanilla IPA version?
##### TODO: Add ability to detect and simplify TIMIT 
##### TODO: Add disclaimer that the above happens 
```

- [x] Add above symbols to `weirds` as TIMIT inclusion 
- [x] Add IPA equivalents (need to verify Unicode codes)
- [ ] Add test data using them 
- [ ] Add IPA examples (without additional special characters)
- [ ] Document dropped variables 
- [ ] Integrate into project 
- [ ] Check for collisions (since some of these simplify to existing ARPAbet)
- [ ] Possibly try turning the additional TIMIT extensions into ARPAbet first?

**Comment by cyrusae** [comment]
Update: nope Past Me already integrated some diacritic handling, buckle up boys we're doing this now
